# Default values for ipu-user-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: advancedpricing.azurecr.io/ipu-user-service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: "amps-docker-secret"
nameOverride: ""
fullnameOverride: "ipu-user-service"

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 2001
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 5001

deployment:
  containerPort: 5001

ingress:
  enabled: true
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
#  path: /ipu-user-service/?(.*)
  # hosts:
  #   - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

app_port: 5001

secret_name: ipu-user-service-secrets

#ENV vars
enable_ingress: false
ipu_db_user: kubernetesipu
ipu_db_password: p@ssw0rd
ipu_db_host: dragon-dev-db.postgres.database.azure.com
ipu_db_port: 6432
ipu_database: ipu_dev
database_database: dragon_dev
database_user: kubernetes
database_password: p@assw0rd
env_name: dev
db_encrypt_key: "FFF6C3C7A726FA8C758130539833D337"
db_encrypt_key_iv: "A18EB6A09CEB0B02FA4F1757BE27713D"
db_key_encrypt_key_iv: "00000000000000000000000000000000"
database_host: dragon-dev-db.postgres.database.azure.com
database_port: 5432