apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ipu-user-service.fullname" . }}
  labels:
    app: {{ template "ipu-user-service.name" . }}
    chart: {{ template "ipu-user-service.chart" . }}
    draft: {{ .Values.draft | default "draft-app" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  revisionHistoryLimit: 5
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "ipu-user-service.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ipu-user-service.name" . }}
        draft: {{ .Values.draft | default "draft-app" }}
        release: {{ .Release.Name }}
      annotations:
        buildID: {{ .Values.buildID | default "" | quote }}
        container.apparmor.security.beta.kubernetes.io/{{ .Chart.Name }}: runtime/default
    spec:
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
            seccompProfile:
              type: RuntimeDefault
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.containerPort }}
              protocol: TCP
          env:
            - name: IPU_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret_name }}
                  key: IPU_DB_USER
            - name: IPU_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret_name }}
                  key: IPU_DB_PASSWORD
            - name: IPU_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret_name }}
                  key: IPU_DB_HOST
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret_name }}
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret_name }}
                  key: DATABASE_PORT
            - name: IPU_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret_name }}
                  key: IPU_DB_PORT
            - name: IPU_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret_name }}
                  key: IPU_DATABASE
            - name: DATABASE_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret_name }}
                  key: DATABASE_DATABASE
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret_name }}
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret_name }}
                  key: DATABASE_PASSWORD
            - name: ENV_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret_name }}
                  key: ENV_NAME
            - name: DB_ENCRYPT_KEY
              valueFrom:
                secretKeyRef:
                   name: {{ .Values.secret_name }}
                   key: DB_ENCRYPT_KEY
            - name: DB_ENCRYPT_KEY_IV
              valueFrom:
                secretKeyRef:
                   name: {{ .Values.secret_name }}
                   key: DB_ENCRYPT_KEY_IV
            - name: DB_KEY_ENCRYPT_KEY_IV
              valueFrom:
                secretKeyRef:
                   name: {{ .Values.secret_name }}
                   key: DB_KEY_ENCRYPT_KEY_IV