apiVersion: v1
kind: Secret
metadata:
    name: "{{ .Values.secret_name }}"
    labels:
        app: {{ template "ipu-user-service.fullname" . }}
type: Opaque
stringData:
    IPU_DB_USER: "{{ .Values.ipu_db_user }}"
    IPU_DB_PASSWORD: "{{ .Values.ipu_db_password }}"
    IPU_DATABASE: "{{ .Values.ipu_database }}"
    DATABASE_DATABASE: "{{ .Values.database_database }}"
    DATABASE_USER: "{{ .Values.database_user }}"
    DATABASE_PASSWORD: "{{ .Values.database_password }}"
    ENV_NAME: "{{ .Values.env_name }}"
    DB_ENCRYPT_KEY: "{{ .Values.db_encrypt_key }}"
    DB_ENCRYPT_KEY_IV: "{{ .Values.db_encrypt_key_iv }}"
    DB_KEY_ENCRYPT_KEY_IV: "{{ .Values.db_key_encrypt_key_iv }}"
    IPU_DB_HOST: "{{ .Values.ipu_db_host }}"
    IPU_DB_PORT: "{{ .Values.ipu_db_port }}"
    DATABASE_HOST: "{{ .Values.database_host }}"
    DATABASE_PORT: "{{ .Values.database_port }}"